### ISSUE TITLE
Preview and Save: image size doesn't match

### ISSUE THREAD

**Issue by eloudsa** [commonsguy/cwac-camera#269]
Hello

I have an issue with the cwac-camera library on a Galaxy Note 10.1:
- version: 4.1.2
- model: GT-N8010

The problem is related to the front camera.

The preview image is different from the picture saved through the library.

To illustrate the problem, I have used the Demo sample application.

I have attached the following pictures:
- pic1-cwac: the image as seen through the Demo application
![pic-cwac](https://cloud.githubusercontent.com/assets/300818/7024541/ee46257c-dd3d-11e4-90bb-9e10b7301447.png)

- pic2-gallery: the image captured and saved as an image file
![pic-gallery](https://cloud.githubusercontent.com/assets/300818/7024542/ee48ae0a-dd3d-11e4-9af3-9dc95ab7581f.jpg)

Is it a way to obtain an image file identical to the preview as done with the native camera?

Thanks

Said

**Comment by commonsguy** [comment]
> The preview image is different from the picture saved through the library.

What specific difference is your concern?

**Comment by eloudsa** [comment]
I was expecting a match between the preview and the saved images: same height and width.

The Android native camera works as expected.

I'm developing an application with the cwac library. I've received some customer feedbacks regarding this issue.

Did you already noticed this issue and do you have any tips to fix it?

**Comment by commonsguy** [comment]
> I was expecting a match between the preview and the saved images: same height and width.

Your apparent preview size is being driven partly by available camera preview sizes, partly by your library settings (e.g., full-bleed preview), and partly by the available space for the `CameraView`. For example, with full-bleed previews, part of the previews are hidden (via negative margins), as the aspect ratio of the `CameraView` has nothing to do with the aspect ratio of the preview image. And neither of those have anything to do with the aspect ratio of the picture itself, which is determined by your chosen picture size. This library does not attempt to guess what aspect ratio you want and change the image to that ratio.

Beyond aspect ratios, the height and width of the picture will frequently be substantially larger than the height and width of any preview, simply because camera resolutions are usually higher than screen resolutions.

> do you have any tips to fix it?

If you do not like the pictures, then you need to change the pictures. For example, if by "same height and width", you really mean "same aspect ratio", then you need to decide for yourself what aspect ratio you want, out of all sorts of candidates:

- the aspect ratio of the preview images
- the aspect ratio of the `CameraView`, taking into account things like the full-bleed preview
- the aspect ratio of the camera images themselves (the behavior that are you presently seeing)
- aspect ratios chosen manually by the user through your UI (e.g., 4:3, 16:9, 16:10)
- the [Golden Ratio](http://en.wikipedia.org/wiki/Golden_ratio)
- etc.

Then, you would need to crop the photo to achieve your desired aspect ratio. You would need to determine which axis needs cropping (horizontal or vertical). The subset you want should be centered within that axis, so cropping an equal amount off of both sides of that axis should give you what you want.

Or, you could integrate [an image cropping library](https://android-arsenal.com/tag/45) into your app and allow the user to directly crop what they want, independent of the preview.

**Comment by eloudsa** [comment]
Thanks!
