### ISSUE TITLE
Position of picture content

### ISSUE THREAD

**Issue by ChristianLJ** [commonsguy/cwac-camera#270]
Hi Commonguy,

Thank you for this amazing library. It is really nice, and easy to use but i have some problems i will try to describe here.

When i take a picture i send it to an API which is going to process the image. The image processing requires that the contents of the image are relatively (to the top, left and right) in the same place no matter the resolution and device.

I have made a camera view with a square borderbox padding 10dp from the top, left and right.
I want this behaviour to be reflected in the taken pictures. I have attached an image of the cameraview and an picture from the camera which i hope can help explain the problem.
I have an idea that this have something to do with the aspect ratio of the preview and the picture, but i am not sure. 

Is this behaviour possible?

Please let me explain further if i did not made my self clear.

Thank you,
Christian Leicht Jørgensen
![1](https://cloud.githubusercontent.com/assets/3056379/7029673/9f3a36f4-dd5f-11e4-82c5-bf093afce094.jpg)
![2](https://cloud.githubusercontent.com/assets/3056379/7029674/9f663b96-dd5f-11e4-9122-325e42efd227.jpg)

**Comment by commonsguy** [comment]
It appears that you are concerned perhaps about differences between the camera preview and resulting images. In that case, you may wish to read [this issue that I closed earlier today](https://github.com/commonsguy/cwac-camera/issues/269) for related information. In short, if you want the output image to have certain characteristics with respect to size or aspect ratio, that's your job, not the job of the library.

Beyond that, if you feel that there is a bug in the library, please explain what the bug is and how to reproduce it, either using the demo app or using some code that you provide.

If you are here for more general support, rather than reporting a bug, please bear in mind that this is an issue tracker. [The documentation](https://github.com/commonsguy/cwac-camera#questions) explains how to get support for the library.

**Comment by ChristianLJ** [comment]
Thank you. I have made a post on StackOverflow. 
Sorry for bloating this issue tracker, and not reading the documentation completely.

http://stackoverflow.com/questions/29498468/preview-and-picture-size-using-cwac-camera
